### PR TITLE
prettified all ugly json under /tests/ per #226

### PR DESCRIPTION
**Pull request by Mika-net**
Prettified all ugly JSON all non integration tests pass numbering 83.

### CODE REVIEW

**Comment by marco-c** [comment]
Tests are failing, so there's likely something wrong in one or more of the files you prettified.

**Comment by Mika-net** [comment]
@marco-c I rolled back the changes locally but still have the same failing test, I'm looking into how to fix it but It looks like the issue is that the expected array isn't matching the result, to test I'm altering the expected to match the actual. This error is in a file that is already formatted prior to this pr. Let me know if you don't have the same issue.

**Comment by marco-c** [comment]
@Mika-net the tests are passing on CI and on my machine. I know setting up the integration tests locally is not that easy unfortunately... @calixteman what were the versions of GCC and LLVM required for integration tests?

A (slow) workaround for you to find the "bad" files would be to push your changes a few at a time and let CI run the tests for you.

**Comment by Mika-net** [comment]
@marco-c  thanks for the feedback! For the tests all I did was cargo build/cargo test. Was there more to the process? I'll start on the slow work around.

**Comment by marco-c** [comment]
The integration tests don't work with all versions of GCC and LLVM, so the requirements to make them pass are pretty strict (see #308 and #258).

**Comment by Mika-net** [comment]
I don't know if this will ping yall alot but I'll let ya know when I'm done isolating the issue via these automated tests

**Comment by Mika-net** [comment]
@marco-c I've tested it with an extremely small change and it throws this, thread 'test_integration' panicked at  
``` called Result::unwrap()` on an `Err` value: Error("EOF while parsing an object", line: 1, column: 1)', src/libcore/result.rs:999:5 ```

Is it possible the integration tests cant parse these JSON files if they're prettified?

**Comment by marco-c** [comment]
> Is it possible the integration tests cant parse these JSON files if they're prettified?

Answered at https://github.com/mozilla/grcov/issues/226#issuecomment-529973994 (the ADE files are not JSON files, but files where each line is a JSON object, so they can't be prettified).

**Comment by Mika-net** [comment]
@marco-c sorry about all the back and forth, but it should  be good now.

**Comment by marco-c** [comment]
Looks good so far, but I think you can also prettify the covdir files.

**Comment by marco-c** [comment]
Also, I think you missed the files under tests/basic/ and tests/switch/.

**Comment by Mika-net** [comment]
For test  basic and switch the only ones not already prettified are the .ade files, and all but one of the .covdir files was already prettified.

**Comment by marco-c** [comment]
Oh, OK!

**Pull request merged**
