### PR TITLE
switch to rust's hashmap

### PR DESCRIPTION
**Pull request by NerdyPepper**
as suggested by #283, this pr contains changes to switch over to rust's `HashMap` from `FxHashMap`.

i don't really know much about benchmarking, so i will leave the performance evaluation to someone with more experience.

### CODE REVIEW

**Comment by marco-c** [comment]
> i don't really know much about benchmarking, so i will leave the performance evaluation to someone with more experience.

You can run the grcov's benchmarks before/after your changes and post the results here, this way we can see if this is improving the results or not.

**Comment by NerdyPepper** [comment]
i have run `cargo +nightly bench` on `mozilla/grcov:master` and `nerdypepper/grcov:hashmap`, and there seems to be a (very) minor improvement. i have attached an image containing the results (i do not know of any other way to share benchmarks at the moment).

img

**Comment by calixteman** [comment]
Maybe you could use: https://github.com/BurntSushi/cargo-benchcmp to get a diff.

**Comment by NerdyPepper** [comment]
thanks for the suggestion @calixteman! i have attached the diff produced by `cargo benchcmp`.

``` name                                           latest ns/iter  hashmap ns/iter  diff ns/iter   diff %  speedup 
 bench_filter_covered                           7               6                          -1  -14.29%   x 1.17 
 bench_filter_covered_functions_executed        7               6                          -1  -14.29%   x 1.17 
 bench_filter_covered_no_functions              6               6                           0    0.00%   x 1.00 
 bench_filter_covered_toplevel_executed         8               8                           0    0.00%   x 1.00 
 bench_filter_uncovered_functions_not_executed  9               9                           0    0.00%   x 1.00 
 bench_filter_uncovered_no_lines_executed       13              11                         -2  -15.38%   x 1.18 
 bench_lib_consumer                             13,509,430      12,484,215         -1,025,215   -7.59%   x 1.08 
 bench_lib_merge_results                        371             386                        15    4.04%   x 0.96 
 bench_output_activedata_etl                    5,339           5,439                     100    1.87%   x 0.98 
 bench_output_covdir                            35,367          35,526                    159    0.45%   x 1.00 
 bench_output_lcov                              32,456          32,266                   -190   -0.59%   x 1.01 
 bench_parser_gcov                              2,036,195       2,134,359              98,164    4.82%   x 0.95 
 bench_parser_jacoco                            31,308,533      30,836,854           -471,679   -1.51%   x 1.02 
 bench_parser_lcov                              39,595,033      38,335,427         -1,259,606   -3.18%   x 1.03 
 bench_reader_finalize_file                     296             349                        53   17.91%   x 0.85 
 bench_reader_finalize_file_branch              2,396           2,920                     524   21.87%   x 0.82 
 bench_reader_gcda                              5,580           5,702                     122    2.19%   x 0.98 
 bench_reader_gcno                              13,621          13,638                     17    0.12%   x 1.00 
 bench_reader_gcno_dump                         11,268          12,044                    776    6.89%   x 0.94 
 bench_reader_gcno_gcda_dump                    13,386          14,434                  1,048    7.83%   x 0.93 
```
`cargo benchcmp` with coloured outputs provides a better visual: 
img

here, **latest** refers to `FxHashMap` and **hashmap** refers to `hashbrown`.

**Comment by marco-c** [comment]
The colors in the diff are the other way around (as I guess you used your PR as the "before" state and the previous code as the "after state :P), so red for better and green for worse.
In general, there doesn't seem to be a big difference :(

**Comment by NerdyPepper** [comment]
ah sorry, that does seem to be the case!

i'm on the same boat regarding the performance @marco-c.

**Pull request closed without merging**
