### PR TITLE
Filter jacoco and info files

### PR DESCRIPTION
**Pull request by calixteman**

### CODE REVIEW

**Comment by calixteman** [comment]
Yes I think too.
Anyway afaik there are not so much jacoco files and if we don't do that it means that we need some extra steps to get gcno/gcda, correct jacoco files, ... so I think it's not a problem to lose few millisecs for that.

**Comment by marco-c** [comment]
On CI we don't have any problem as we set GCOV_OUTPUT_DIR, so this is only going to slow down that use case.

**Comment by calixteman** [comment]
So we could add an option "--check-files" or something like that. Wdyt ?

**Comment by marco-c** [comment]
I'd say the perf hit is so small that we can ignore it.

**Pull request merged**
