### PR TITLE
Add cobertura output option

### LINKED ISSUE #468: Generate coverage output for Gitlab/Cobertura?
Would it be possible to add support for generating Cobertura xml coverage reports? [Gitlab's coverage reporting](https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html) uses Cobertura's format.

It appears as though [tarpaulin supports cobertura](https://github.com/xd009642/tarpaulin#pycobertura), so it would be good if `grcov` could too.

### PR DESCRIPTION
**Pull request by geovie**
Hi,
this PR adds a new output option for the cobertura xml format (as defined in http://cobertura.sourceforge.net/xml/coverage-04.dtd).

I only did some basic testing, so I'm not sure how correct the output is, but it should be a good starting point for now.

Fixes #468

### CODE REVIEW

**Review by marco-c — COMMENTED** [review]
I didn't do a super careful review since it's a new output format, but it looks good overall.
Can you add some basic tests though? You can write tests for the `output_cobertura` function directly, making sure the cobertura output is what you'd expect given the coverage data you pass in.

**Comment by geovie** [comment]
@marco-c Added some tests and fixed the coverage stats.
Previously it could happen that the stats were wrong if e.g. two function with the same lines are reported the lines would be counted twice.

**Review by marco-c — APPROVED** [review]
Thanks!

**Comment by marco-c** [comment]
@geovie would you like to document how to use grcov with GitLab?

**Comment by svenstaro** [comment]
I'd much appreciate a new release of grcov with this PR in it. :)

**Comment by marco-c** [comment]
@svenstaro I've released 0.8.0.

**Comment by svenstaro** [comment]
Super nice, thanks!

**Pull request merged**
